[package]
name = "brog"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"

dotenv = "0.15.0"
dotenvy = "0.15.7"
reqwest = "0.12.9"
serde_yaml = "0.9.34"
tokio = { version = "1.17.0", default-features = false, features = [
    "macros",
    "rt-multi-thread",
    "time",
] }
tokio-cron-scheduler = { version = "0.13.0", features = ["english"] }
tracing = { version = "0.1.40", features = ["log"] }
tracing-subscriber = { version = "0.3.18", features = [
    "registry",
    "env-filter",
] }
